name: Development build artifact

on:
  push:
    branches: [ master ]

jobs:
  dev-release:
    name: Development Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: cache-lein-deps
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('project.clj') }}
      - name: Setup test database
        run: docker-compose up -d
      - name: Build & test
        run: |
          lein deps
          lein test
          lein uberjar
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          files: |
            LICENSE
            target/uberjar/*.jar
