name: Deploy to staging on a VPS

on: [ push ]

jobs:
  call-test-workflow:
    uses: ./.github/workflows/test.yml
  call-build-workflow:
    needs: call-test-workflow
    uses: ./.github/workflows/build-uberjar.yml
  deploy-to-staging:
    needs: call-build-workflow
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: bugle-forms-uberjar
        path: target/uberjar
    - name: Setup ssh
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.STAGING_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        echo "${{ secrets.STAGING_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
    - name: Deploy with docker compose
      env:
        DOCKER_HOST: ${{ format('ssh://{0}@{1}', secrets.STAGING_USER, secrets.STAGING_HOST) }}
        ENVIRONMENT: staging
        COMPOSE_DOCKER_CLI_BUILD: 0
      run: |
        docker-compose -f deploy.yml down
        docker-compose -f deploy.yml up --build -d
