name: Deploy to production on Heroku

on:
  push:
    branches: [ master ]

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build-uberjar.yml
  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: call-build-workflow
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: bugle-forms-uberjar
        path: target/uberjar
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: bugle-forms-production
        heroku_email: atharva@nilenso.com
        usedocker: true
